### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by ysm0622** [yangshun/front-end-interview-handbook#12]
Hi, I'm Chris from Korea.

Would you mind if I translate this repo into Korean?

**Comment by yangshun** [comment]
Hey @ysm0622 , definitely not. But how do you intend to keep it in sync as updates roll in?

**Comment by ysm0622** [comment]
I plan to `watch` this repo, and try to keep it in sync.

Which way do you prefer `[Fork this repo]` or `[new repo + translation reference in README.md]`?

**Comment by yangshun** [comment]
I think it'll be easier to just work in this repo. Just invited you into it (:

**Comment by ysm0622** [comment]
Please invite him, too. @devJang

Thank you.

**Comment by ysm0622** [comment]
@yangshun !

Please add one more collaborator, @tuhbm

**Comment by yangshun** [comment]
Done!

**Comment by yangshun** [comment]
Hey all, I have created a `translations/kr` subfolder for you guys. In general, if you are doing translations, please do not modify anything outside of that folder without discussion. You are free to do whatever you like within that subfolder. cc @HaitianLiu for the chinese version, you can create a `translations/zh` or `cn` you deem fit 😄 

Note that I will split up each section into its own README. It is up to you whether you want to do the split as well.

**Comment by ysm0622** [comment]
@yangshun Thank you ! 🙏

**Comment by HaitianLiu** [comment]
OK, I'm doing something just like you said.
