### ISSUE TITLE
incorrect character in chinese

### ISSUE THREAD

**Issue by tso1158687** [yangshun/front-end-interview-handbook#130]
I found typo in the Chinese version of javascript chapter about 请解释变量提升（**hosting**）
hosting->hoisting

**Comment by pugok9** [comment]
Pugok PancaAssaafJr PancaAssaaf Kemensetnegri Foxnews Usatoday Jokowi Realdonaldtrump Billgates Markzukerg Britneyspears MikeBloomberg donaldjtrumpjr

**Comment by yangshun** [comment]
Closed by #139
