### ISSUE TITLE
CSS question missing from links

### ISSUE THREAD

**Issue by helplah** [yangshun/front-end-interview-handbook#132]
The following question was missing from the list of links above:

**How is responsive design different from adaptive design?**

**Comment by yangshun** [comment]
@helplah Thanks! Wanna send in a PR to fix it? Help lah 😄

**Comment by helplah** [comment]
@yangshun can can... done liao haha

**Comment by yangshun** [comment]
Nice to interact with fellow Singaporeans on GitHub. Many thanks! 🎉
