### ISSUE TITLE
Is there any alternative repository for back-end ?

### ISSUE THREAD

**Issue by nakorndev** [yangshun/front-end-interview-handbook#15]
Sorry, this may not issue the content of this repository and my English not so strong. But as a title I asked for, I try to search many repositories there has only a question for an interview, not a handbook, as this https://github.com/arialdomartini/Back-End-Developer-Interview-Questions The contents are not contained about any answer for it. I really confuse a question also couldn't manage to find out any answer for it, as well as I am a little rookie for programmable.

Anyways thanks for the nice repository. This documentation really made me learn many things like a getting started guideline 👍

**Comment by yangshun** [comment]
Sorry not that I know of. This repository was born out of the frustrations of a lack of answers for front end questions as well. Perhaps you could start a repository to start answering those back end questions (:
