### ISSUE TITLE
Add PT-BR (Brazilian Portuguese) translations

### ISSUE THREAD

**Issue by mateusmlo** [yangshun/front-end-interview-handbook#154]
I'll be translating the questions to PT-BR but I don't promise it will be fast. Will probs start working on it later this weekend, which includes forking the original repo and stuff. I hope to be of great help to this already helpful project

**Comment by portolucas** [comment]
If you will need help, contact me.

**Comment by yangshun** [comment]
PRs welcome. I will not actively seek translations for other languages, interested parties can create PRs with some implementation efforts.
