### ISSUE TITLE
On the difference between Classes ES6 and Factories ES5

### ISSUE THREAD

**Issue by MarcosX** [yangshun/front-end-interview-handbook#16]
Hi everyone,

First of all, great job with this repo. I found the information here extremely useful (even if it's not for an interview prep).

I was reading about the difference between constructors and factories in JS and found this blog post to be quite useful: https://medium.com/javascript-scene/javascript-factory-functions-vs-constructor-functions-vs-classes-2f22ceddf33e.

My attempt at answering the question (based on that text and its references) would be:

From a practical point of view, the main difference are how to instantiate new objects and what `this` refers to when creating them.

Classes are a syntax sugar for Constructor functions, which basically define a new object and append functions to its prototype. This allows developers to instantiate objects using `new` and also ensure that `this` inside the class refers to the object being created (similar to other languages).

```javascript
class ClassCar {
  drive () {
    console.log('Vroom!');
  }
}

const car1 = new ClassCar();
console.log(car1.drive());
```

Factories are functions that return the new object, which gives developers a bit more freedom on how the object will be instantiated (if more than just creating the object is needed, like pooling). Since factories are just regular functions `this` won't refer to the object being created.

```javascript
const proto = {
  drive () {
    console.log('Vroom!');
  }
};

function factoryCar () {
  return Object.create(proto);
}

const car3 = factoryCar();
console.log(car3.drive());
```

There are more differences, specially regarding the code design of the application which are explored deeper at [Eric Elliot's post](https://medium.com/javascript-scene/javascript-factory-functions-vs-constructor-functions-vs-classes-2f22ceddf33e), if you want to know more about the implications of using Classes or Factories, I recommend checking it out.

###### References
https://medium.com/javascript-scene/javascript-factory-functions-vs-constructor-functions-vs-classes-2f22ceddf33e

**Comment by denniscual** [comment]
Nice suggestion @MarcosX . I think this information is good to add on the question list. What do you think @yangshun ?
