### ISSUE TITLE
HTML rendering and Browser Architecture.

### ISSUE THREAD

**Issue by revanth0212** [yangshun/front-end-interview-handbook#175]
Knowing more about how rendering happens is very important. With the latest JS frameworks, it has become very vague for new developers to know what is happening in the HTML world as they generate HTML in JS using JSX. I felt these questions would definitely introduce certain topics that they can read on at their own pace.

https://github.com/yangshun/front-end-interview-handbook/pull/174

**Comment by yangshun** [comment]
As mentioned in #174, I would want to mirror the questions in https://h5bp.org/Front-end-Developer-Interview-Questions/questions/html-questions/.
