### ISSUE TITLE
Template literal terminology

### ISSUE THREAD

**Issue by travismeyer** [yangshun/front-end-interview-handbook#19]
In the section **What kind of things must you be wary of when designing or developing for multilingual sites?**, you warn against using concatenated strings, and suggest using template parameters instead. 

By template parameters, do you mean template literals or tag functions? 

Thanks for your work on this, this is a great document!

**Comment by yangshun** [comment]
I do mean template parameters, such as passing parameters into a [handlebars template](http://handlebarsjs.com/) and [lodash templates](https://lodash.com/docs/4.17.4#template). These templating "engine"s will escape the values for you, unlike in using template literals. I should probably be clearer about it though.
