### ISSUE TITLE
README split

### ISSUE THREAD

**Issue by carlosnufe** [yangshun/front-end-interview-handbook#21]
Hey there 👋 !

I ran into this wonderful repository because one of the stargazers is [Marius Schulz](https://github.com/mariusschulz). So, I would like to contribute adding a little bit of organisation. 

To accomplish that I would like to propose splitting up the README into the different current sections. That action would give us more maintainability, readability, scalability. 

Furthermore, I would like to propose adding some anchors to improve navigation which now is tough and poor.

Hard work but to be honest, it would be appealing to the current and new contributors.

**Comment by yangshun** [comment]
I agree. https://github.com/h5bp/Front-end-Developer-Interview-Questions has just split into individual sections as well. I'll work on this when I get the time 👍
