### ISSUE TITLE
May I translate this in Chinese?

### ISSUE THREAD

**Issue by HaitianLiu** [yangshun/front-end-interview-handbook#23]
Hi, I saw a Korean version in the repo, may I do a Chinese version?
If you can, invite me plz.

**Comment by yangshun** [comment]
Ok sure. But I intend to do some restructuring as per #21 , so watch out for that.

**Comment by HaitianLiu** [comment]
Thanks for reminding, I will be careful for that.

**Comment by wencheng256** [comment]
@HaitianLiu Hai where is your Chinese translation？

**Comment by yangshun** [comment]
It's here - https://github.com/yangshun/front-end-interview-handbook/tree/master/translations/zh-cn

**Comment by HaitianLiu** [comment]
I think it’s better to add an entry for translation on homepage when finished.

**Comment by yangshun** [comment]
Sure. I'll file an issue

**Comment by wencheng256** [comment]
Thanks for all your work！ @HaitianLiu @yangshun

**Comment by jeasonstudio** [comment]
@HaitianLiu @yangshun I am interested in some of these js-questions, so I translated some.  
see: [https://zhuanlan.zhihu.com/p/33924633](https://zhuanlan.zhihu.com/p/33924633)

**Comment by yangshun** [comment]
@jeasonstudio Feel free to make a pull request

**Comment by HaitianLiu** [comment]
@jeasonstudio Thanks, it's helpful. I will push CSS part today. As @yangshun mentioned, feel free.
