### ISSUE TITLE
Recommended grid system

### ISSUE THREAD

**Issue by maeligg** [yangshun/front-end-interview-handbook#24]
Thanks for creating this repo, it's very complete and useful.
So this is somewhat a matter of personal preference, but I would suggest you change your response to "Have you ever used a grid system, and if so, what do you prefer?" from float to flexbox. Support for flexbox is now very good, including IE11 https://caniuse.com/#search=flexbox
The latest version of Bootstrap also uses flexbox for its grid (with no fallback that I'm aware of) https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by mihhu** [comment]
I second that! Also, I believe the same could be said about [grid](https://caniuse.com/#feat=css-grid).

**Comment by yangshun** [comment]
Thanks, fixed in 6830fb0.
