### ISSUE TITLE
Correnction to "Explain how prototypal inheritance works" answer

### ISSUE THREAD

**Issue by matrixersp** [yangshun/front-end-interview-handbook#270]
"All JavaScript objects have a __proto__ property" with the exception of objects created with `Object.create(null)`.

**Comment by GouravSingal-code** [comment]
hey can I contribute

**Comment by hawkeye126** [comment]
@matrixersp @yangshun https://github.com/yangshun/front-end-interview-handbook/pull/305

**Comment by yangshun** [comment]
Closed via #305 thanks to @hawkeye126!
