### ISSUE TITLE
Filipino Translation [TL Repository]

### ISSUE THREAD

**Issue by cordeta** [yangshun/front-end-interview-handbook#29]
Hi , permit me to translate all your files for tagalog Filipino [PHILIPPINES] localization. Rest assured that my work is credible. Thanks .

proposed repo : 
front-end-interview-handbook/tree/master/translations/tl_PH

i will wait for your go signal @yangshun

**Comment by yangshun** [comment]
Sure, please follow existing format.

**Comment by cordeta** [comment]
I will.  Thank You
