### ISSUE TITLE
deepClone vs shallowClone for JS Questions

### ISSUE THREAD

**Issue by Aghassi** [yangshun/front-end-interview-handbook#31]
It may be of interest to add a question on deep cloning vs shallow cloning for the JS section. It can be extremely important for a programmer to know the difference as it has a huge impact on performance.

**Comment by yangshun** [comment]
That's an interesting question. As much as possible, we try to keep our questions in sync with the original questions repository. Perhaps you could create an issue and suggest it at https://github.com/h5bp/Front-end-Developer-Interview-Questions first?

**Comment by yangshun** [comment]
Please reopen this or create another issue if and when the question has been added to the questions repository.
