### ISSUE TITLE
How to describe the difference between Cookie, SessionStorage and LocalStorage in coherent paragraph?

### ISSUE THREAD

**Issue by MenaiAla** [yangshun/front-end-interview-handbook#310]
When the interviewer asks me to describe the difference between *`Cookie`*,*`SessionStorage`* and *`LocalStorage`*, my answer will be a short form and consistent expression that identifies the most important keys. However, it's so hard for me ( non-native speaker ) to identify the difference between them in coherent and consistent paragraph. 

For that reason, I'd recommend to transform the table into complete and consistent paragraph.

**Comment by yangshun** [comment]
The answers here are not meant for you to regurgitate during interviews. It's more for knowledge and learning and a tabular format is more efficient for that purpose.

Even for non-native English speakers, they should not have an issue explaining the differences. You can try saying: 

> We will look at the differences in the following axis: A, B, C. In terms of axis A: cookies is X, localStorage is Y, sessionStorage is Z. In terms of axis B, etc..
