### ISSUE TITLE
Cookie is not available only in the client side

### ISSUE THREAD

**Issue by MenaiAla** [yangshun/front-end-interview-handbook#312]
In the answer of the question : Describe the difference between SessionStorage, LocalStorage and cookie , you've mentioned:

> All the above-mentioned technologies are key-value storage mechanisms on the client side. 

While we can use cookies in the server side by sending `Set-Cookie` to the user agent from the server in the response of the header.So, the user agent can send it back to the server late.

**Comment by yangshun** [comment]
> While we can use cookies in the server side by sending Set-Cookie to the user agent from the server in the response of the header. So, the user agent can send it back to the server late.

Yes but the source of truth is still on the client. Cookies passed to the server doesn't mean it's not stored on clients. Clients and delete the cookies anytime they want, so it's still a client-side storage mechanism. Cookies are not stored in databases, so they're on the client.

Definition of cookie from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies):

> An HTTP cookie (web cookie, browser cookie) is a small piece of data that a server sends to a user's web browser. The browser may store the cookie and send it back to the same server with later requests.

So I think that line is still accurate.
