### ISSUE TITLE
`text-indent: -9999px` is popular but not a perfect method

### ISSUE THREAD

**Issue by MenaiAla** [yangshun/front-end-interview-handbook#314]
## Description

When we want to hide a `text` we set its position off screen but do we know what happens behind the scenes?

## Explanation

When we set `text-indent:-9999px`, the browser need to draw a big 9999px box off screen which decreases the performance.

## Alternative  solution

[Jeffrey Zeldman](http://www.zeldman.com/2012/03/01/replacing-the-9999px-hack-new-image-replacement/) suggested to replace -9999px by 100% and his arguments are:

**Comment by AndyNotfound** [comment]
I've never known about this before

**Comment by yangshun** [comment]
Thanks, good to know. Fixed this in 5d112d1. These days I'd recommend using the CSS clip method instead ([source](https://webaim.org/techniques/css/invisiblecontent/))
