### ISSUE TITLE
How do I answer the questions that I don't know them?

### ISSUE THREAD

**Issue by MenaiAla** [yangshun/front-end-interview-handbook#315]
When I was reading the hand-book, I've noticed that most of the answers are positives which enforce the candidates to **memorize** the answers ( Including me ).

However, I'm not a genius yet to know 100% of tips & tricks and answer everything. Also, I don't want to fall in the loop of learning new thing while I'm under pressure to prepare for the interview based on my skills and experience.

For example, I've 1% experience of working with SVG. How do I answer the question : 

**Are you familiar with styling the SVG?** 

While I'm not familiar with it!

**Comment by yangshun** [comment]
Front end technologies (and technologies in general) are very broad and there's nothing wrong to not know about a particular technology/area. You can simply say that you don't know. But if you have listed something down in your resume you better be able to talk about it.
