### ISSUE TITLE
[bug] Site doesn't open

### ISSUE THREAD

**Issue by kartikjagdale** [yangshun/front-end-interview-handbook#335]
![image](https://user-images.githubusercontent.com/7275347/151358778-a7620a5a-670f-4b0c-a4f8-7336f8fab113.png)

**Comment by yangshun** [comment]
Hmm works for me. Could you try again? @kartikjagdale

**Comment by kartikjagdale** [comment]
@yangshun Seems like need to connect via VPN in India. works fine via VPN. 
It seems my Local Service provided has blocked the IPs of the country the website is hosted in.

No issues. I can access it via VPN.

Closing issue.

**Comment by yangshun** [comment]
Hmm I see. Maybe I shall move the hosting to Vercel
