### ISSUE TITLE
Nonstop console errors from carbon ads 

### ISSUE THREAD

**Issue by robert-westenberger** [yangshun/front-end-interview-handbook#343]
If you open the dev console you'll see the following errors, looping forever

**Chrome**
Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at c4f5d8e4.a1ffd138.js:2:872
    at Array.forEach (<anonymous>)
    at c4f5d8e4.a1ffd138.js:2:846

**Firefox**
Uncaught TypeError: t.id is undefined
   t https://www.frontendinterviewhandbook.com/assets/js/1be78505.d182240e.js:1
   t https://www.frontendinterviewhandbook.com/assets/js/1be78505.d182240e.js:1

Appears to have to do something called "carbonads" on the page.

**Comment by yangshun** [comment]
Thanks for reporting! Fixed in 61268b0
