### ISSUE TITLE
Link missing

### ISSUE THREAD

**Issue by induratized** [yangshun/front-end-interview-handbook#347]
This link is missing : https://github.com/yangshun/front-end-interview-handbook/blob/main/contents/en/javascript-questions.md

**Comment by tahseenio** [comment]
@induratized It exists here https://github.com/yangshun/front-end-interview-handbook/blob/main/contents/javascript-questions.md

How did you manage to get that link?

**Comment by induratized** [comment]
I gave sometime to recall where I found it looking in the site but I cannot find it.
I while look more while skimming through the site and will let you know in this thread.
The only difference in the URL is the `/en` part before the `.md` file
