### ISSUE TITLE
"back to top" button does not work.

### ISSUE THREAD

**Issue by asifurrahaman754** [yangshun/front-end-interview-handbook#356]
"back to top" button does not work. I would like to fix it

**Comment by yangshun** [comment]
It works for me. Can you provide some repro instructions? Wouldn't mind a fix of course!

Try the following:
- Try with another browser
- Try with incognito. Make sure your browser extensions are not messing with the page

**Comment by asifurrahaman754** [comment]
I have tries with other browser and in incognito mode. But still not working

**Comment by asifurrahaman754** [comment]
I think the problem is in the ul element. I don't see any id with the name "table-of-contents". I added an id in the ul in devtool and it's working.

**Comment by yangshun** [comment]
Sorry I misunderstood which button you were referring to. You're right, it's not working. But maybe we don't need it anymore since Docusaurus comes with a global back to top button (at the bottom right, scroll up slightly to display it). WDYT?

**Comment by asifurrahaman754** [comment]
Yes, you are also right, so should I delete it and make a pr?

**Comment by asifurrahaman754** [comment]
done, made a pr
