### ISSUE TITLE
multi-language feature is not working

### ISSUE THREAD

**Issue by Bhanu-code** [yangshun/front-end-interview-handbook#373]
Screenshot

![image](https://user-images.githubusercontent.com/77599001/232280239-53e99762-bb15-4697-bf88-8442984f8097.png)

**Comment by Bhanu-code** [comment]
please assign me this issue, I can make multi langauge support by inheriting google translate.

**Comment by yangshun** [comment]
It's working as intended. Only certain pages are translated

**Comment by Bhanu-code** [comment]
oh, great.
