### ISSUE TITLE
Wrong way to set child's prototype

### ISSUE THREAD

**Issue by somyanath** [yangshun/front-end-interview-handbook#380]
https://github.com/yangshun/front-end-interview-handbook/blob/a02793fdbdb0736d1959e4ecc91cc2f5641d769e/packages/quiz/questions/explain-how-prototypal-inheritance-works/en-US.mdx#L26

The above written code will show wrong output, this is not how we assign a prototype of a child to a parent's prototype.

Instead we need to do this:
`Object.setPrototypeOf(Dog.prototype, Animal.prototype);`

**Comment by somyanath** [comment]
@yangshun, let me know if my suggested changes needs more explanation, because according to my understanding the way I have suggested is the correct way to assign prototype.

**Comment by yangshun** [comment]
Thanks for your suggestions, we've fixed it in d24b5d8
