### ISSUE TITLE
Questionable information about localStorage

### ISSUE THREAD

**Issue by thanhsonng** [yangshun/front-end-interview-handbook#384]
Hi, first off thank you very much for the awesome handbook. I am learning a lot from it. However, there is one question which I think could be improved, unless I'm missing something. 

In [this quiz](https://github.com/yangshun/front-end-interview-handbook/blob/main/packages/quiz/questions/describe-the-difference-between-a-cookie-sessionstorage-and-localstorage/en-US.mdx) **Describe the difference between a cookie, sessionStorage and localStorage**, it says the data in localStorage is accessible by other sites. I think this can be misleading. 

As far as I know, localStorage data from one site cannot be accessed from another site. For example, `www.foo.com` cannot read localStorage data of `www.bar.com`. However, if there are multiple tabs accessing `www.foo.com`, they can all access the same localStorage data, and this is the key difference from sessionStorage.

This is the [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) for reference. I'm happy to be proven wrong though.

**Comment by yangshun** [comment]
Fixed in #382
