### ISSUE TITLE
First Sentence of Readme

### ISSUE THREAD

**Issue by robwdev** [yangshun/front-end-interview-handbook#4]
Correct me if I am wrong, but I think you want to refer to the "DOM" (Document Object Model) int he first sentence, not "Domain".

Unlike typical software engineer job interviews, front-end job interviews have less emphasis on algorithms and have more questions on intricate knowledge and expertise about the domain

Unlike typical software engineer job interviews, front-end job interviews have less emphasis on algorithms and have more questions on intricate knowledge and expertise about the DOM (Document Object Model).

**Comment by yangshun** [comment]
No, I do mean domain, as in Front End domain/scene itself. Thanks for clarifying though 😄
