### ISSUE TITLE
Invalid Link in Quiz `what-is-a-closure-and-how-why-would-you-use-one`

### ISSUE THREAD

**Issue by Yatin-kathuria** [yangshun/front-end-interview-handbook#400]
The link provide for Module pattern is not exist not. Please update.
This the old link https://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript. I am not sure about new link.

**Comment by yangshun** [comment]
Thanks, this has been fixed. The new link is: https://www.patterns.dev/vanilla/module-pattern
