### ISSUE TITLE
Maybe we need some guidelines for translation.

### ISSUE THREAD

**Issue by HaitianLiu** [yangshun/front-end-interview-handbook#45]
I want to shorten [this](https://developer.mozilla.org/zh-CN/docs/Glossary_of_translation#%E8%AF%AF%E8%A7%A3%EF%BC%9A100_%E7%BF%BB%E8%AF%91_%E5%87%86%E7%A1%AE) to make a brief principle for zh-cn translators. How about adding a link in [this contributing](https://github.com/yangshun/front-end-interview-handbook#contributing) part?

**Comment by yangshun** [comment]
I'll work on a CONTRIBUTING doc along with guidelines for translations

**Comment by yangshun** [comment]
Fixed via #46
