### ISSUE TITLE
Can you give an example of an @media property other than screen?  TODO

### ISSUE THREAD

**Issue by zamber** [yangshun/front-end-interview-handbook#6]
It can be used for using a 1x or 2x sprite sheet depending on pixel density IIRC.

https://www.google.pl/search?q=media+css+pixel+ratio

**Comment by royledford** [comment]
@media queries support 4 different types; all, screen, print, and speech. It is quite common for a site to provide different styles for pages that would be printed; different color schemes (B&W) maybe required, hiding background images, as well as addressing hidden information that could be relevant when printed.

There are some other types but they will be removed in the css level 4 spec.

Ref: https://www.w3schools.com/cssref/css3_pr_mediaquery.asp

**Comment by yangshun** [comment]
As mentioned by @royledford, the other @media properties are non-standard and won't be supported. The current answer is sufficient.
