### ISSUE TITLE
Position absolute doesn't cause reflow.

### ISSUE THREAD

**Issue by prashanth1509** [yangshun/front-end-interview-handbook#69]
Hey Yangshun & team,

Just a quick clarification about this answer:
https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/css-questions.md#is-there-any-reason-youd-want-to-use-translate-instead-of-absolute-positioning-or-vice-versa-and-why

Changes to position absolute will not cause reflow (recalculation of layout) and the reason being they are already separated from normal flow. 
They do trigger repaint (and composite).

To extend the original answer:
- Translate also avoids pixel snapping (https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/)

**Comment by EnixCoda** [comment]
Hi @prashanth1509 
I investigated a [demo](https://codepen.io/chriscoyier/pen/pBCax) about this and found that reflow did happen in each frame:
![image](https://user-images.githubusercontent.com/7480839/37250648-5ee0e40e-253c-11e8-9166-b1bb2f1e05b2.png)

Can you provide a demo that absolute positioning doesn't cause reflow?😃

**Comment by prashanth1509** [comment]
Hey,
I meant absolute positioning doesn't cause reflow of other elements.
Obviously, when moving the given element, browser needs to recalculate layout for that element (that you see in profiling) and it doesn't cause recalculation of styles, layout for other elements.

https://developers.google.com/speed/docs/insights/browser-reflow (Under guidelines)
https://stackoverflow.com/a/7339211/1125029

**Comment by prashanth1509** [comment]
But given the context of which is better way of animation, 
translate is better because as it doesn't cause layout neither on itself nor on other elements, but position absolute causes layout for itself.
