### ISSUE TITLE
Clarification for domain on localstorage and sessionstorage

### ISSUE THREAD

**Issue by NochEinKamel** [yangshun/front-end-interview-handbook#7]
Hi,
I was reading through the questions and came across "Describe the difference between a cookie, sessionStorage and localStorage".

In the answer it says:  Have domain associated | Yes | No | No

I think that's misleading, as localStorage and sessionStorage are associated to a domain and you can't read storage objects from other domains.
See https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

>  Pages on other domains can't access the same storage objects.

Other than that and what I read so far a great list - especially that it provides answers is a valuable learning experience for everyone.

**Comment by styfle** [comment]
I thought the same thing. I think a better word than domain is “origin” which includes domain.

**Comment by yangshun** [comment]
Thanks, I'm not sure why I wrote that in the first place. I might have been thinking about something else but wrote down the wrong field. Anyway I can't remember what I was thinking of, so I've deleted that line of comparison.
