### ISSUE TITLE
Disadvantages of Ajax

### ISSUE THREAD

**Issue by prashanth1509** [yangshun/front-end-interview-handbook#70]
https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md#what-are-the-advantages-and-disadvantages-of-using-ajax

One more disadvantage you might consider is,
- Its hectic for low-spec mobile devices (clients) to parse and compile huge chunk of javascript to render initial content, but for server rendered app, server (usually high-spec) takes over the responsibility of rendering initial html content.

**Comment by yangshun** [comment]
Thanks, addressed in 6ff3921. In future do consider sending a PR directly 😄
