### ISSUE TITLE
Indonesian Translation [id - localization]

### ISSUE THREAD

**Issue by iqbaladan** [yangshun/front-end-interview-handbook#72]
Hi @yangshun, I am Iqbal Adan from Indonesia. I really want to contribute in translating this project into my native language (Bahasa Indonesia), Would you mind if I translate this project into Bahasa? Waiting forward your response.

**Comment by yangshun** [comment]
No problem, you can fork the repository and start translating

**Comment by iqbaladan** [comment]
Cool, I will follow the format at `front-end-interview-handbook/CONTRIBUTING.md`
