### ISSUE TITLE
localstorage may be related with domain

### ISSUE THREAD

**Issue by ckmilse** [yangshun/front-end-interview-handbook#79]
localstorage应该与域名相关吧

https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage

**Comment by xaclincoln** [comment]
从标准上看，LocalStorage 和 SessionStorage与Origin关联

**Comment by HaitianLiu** [comment]
Yes, I just had an interview and asked me this. I will update Chinese version tonight. Sorry for late response.
