### ISSUE TITLE
Can you explain the difference between coding a web site to be responsive versus using a mobile-first strategy?  TODO

### ISSUE THREAD

**Issue by zamber** [yangshun/front-end-interview-handbook#8]
Mobile-first is easily doable with CSS frameworks (media-query specific classes), scales smoothly, does hide stuff that's not needed on feature phones, mobiles and tablets from the get-go or has device-specific UX like the beloved hamburger menu. You actually can develop with the viewport adapted for your mobile target.

I also tend to actually test stuff on devices. Handling an adapted viewport with a mouse hides UX issues that can be easily found when you load up the page on your phone.

"Responsive" can be an afterthought. I've seen pages with fixed-width inline styles (React, I'm looking at you) where making them responsive is a low-prio feature in the backlog. Depending on the creativity of the original dev adding this "feature" can be a nightmare.

**Comment by royledford** [comment]
I feel this is a little bit of a trick question as "responsive web design" is a technique that allows a web site to adjust and change based on the width and size of the browser. Css media queries are typically used to determine the screen width and items may be hidden, resized and/or re-ordered as the width of the browser window changes.

An alternative to responsive is a fluid layout. Fluid layouts generally reflow the page containers width and height without hiding or disabling features on to fit smaller screen sizes. 

"Mobile First" is a design strategy. In mobile first, the site design is based on the limitations of a supported range of mobile devices. Starting with mobile constraints forces the design to focus on presenting relevant content to the user over flashy effects. Progressive enhancement is used to add features, effects and sometimes additional content as the screen space grows. A mobile first design will be responsive once those additional features are added.

Sites that are designed starting at the desktop size follow the opposite strategy of "mobile first". The design focuses on the desktop sizes and features that are available on that platform. "Graceful degradation" is then used to remove/adjust features as the screen width is reduced.

Whether you start with mobile or desktop as a design strategy, providing support for various screen widths results in a responsive web site.

**Comment by yangshun** [comment]
Fixed in #111
