### ISSUE TITLE
Memory implications of using closure methods vs prototype methods

### ISSUE THREAD

**Issue by mastef** [yangshun/front-end-interview-handbook#9]
Which of these is more memory efficient, and why?

```js
function ProtoPerson() {}

ProtoPerson.prototype.getName = function() {
	return "MyName";
};

ProtoPerson.prototype.getLink = function() {
	return "http://mycompany.com/myLinks/" + this.getName();
};

var protoPersons = [];
for (var i = 0; i < 100000; i++) {
	protoPersons.push(new ProtoPerson);
}
```

```js
function ClosurePerson() {

	this.getName = function() {
		return "MyName";
	};

	this.getLink = function() {
		return "http://mycompany.com/myLinks/" + this.getName();
	};

}

var closurePersons = [];
for (var i = 0; i < 100000; i++) {
	closurePersons.push(new ClosurePerson);
}
```

**Comment by skant09** [comment]
The first one. 
When you define a public method on the prototype of class/function it gets shared by its instances. While public methods/members defined on instances e.g. `this.getName`, is generated for each instance separately.
That also means that any instance is able to override/change prototype methods. Which can be dangerous in a shared memory scenario.
http://yehudakatz.com/2011/08/12/understanding-prototypes-in-javascript/

**Comment by yangshun** [comment]
Please refer to our guidelines on [submitting new questions](https://github.com/yangshun/front-end-interview-handbook/blob/master/CONTRIBUTING.md#submitting-new-questions). Thanks!
