### ISSUE TITLE
ES6 String Duplicate

### ISSUE THREAD

**Issue by xgqfrms-gildata** [yangshun/front-end-interview-handbook#95]
# ES6 String Duplicate

https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md#make-this-work

![image](https://user-images.githubusercontent.com/29531779/37387799-d9289e4c-2798-11e8-84d2-2a960db9d8c7.png)

```js

/**
 * @author xgqfrms
 * @license MIT
 * @description ES6 String Duplicate
 * @param {Array} arr
 */

let arr = [1, 2, 3, 4, 5];
const ES6_String_Duplicate = arr => `${arr.toString()},`.repeat(2).slice(0, -1).split(`,`).map(item => parseInt(item));
ES6_String_Duplicate(arr);
// (10) [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

```

**Comment by yangshun** [comment]
I'm sorry but this approach is convoluted and longer than it needs to be. I would rather not add this in.

**Comment by xgqfrms-gildata** [comment]
OK, fine!
