### ISSUE TITLE
"JSON" & "XML" inverted in answer

### ISSUE THREAD

**Issue by oxcarga** [yangshun/front-end-interview-handbook#98]
https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md#explain-ajax-in-as-much-detail-as-possible

Correctly if I'm wrong but I guess those are inverted

> modern implementations commonly substitute **JSON for XML**

Sholdn't it be 

> modern implementations commonly substitute **XML for JSON**

?

**Comment by yangshun** [comment]
You're absolutely right. Would you like to make a PR to fix it? 😄

**Comment by FrodoLuo** [comment]
Also, the Chinese translation of this sentence is still wrong.
